# Generated by Django 2.0.7 on 2018-07-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
